# Generated by Django 2.2.7 on 2020-07-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Postion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wolf', models.PositiveIntegerField()),
                ('citizen', models.PositiveIntegerField()),
                ('hunter', models.PositiveIntegerField()),
                ('diviner', models.PositiveIntegerField()),
                ('traitor', models.PositiveIntegerField()),
                ('psychic', models.PositiveIntegerField()),
            ],
        ),
    ]
