# Generated by Django 2.2 on 2019-07-19 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wolf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=15)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wolf.Player_Name')),
            ],
        ),
        migrations.CreateModel(
            name='How_Many',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wolf.Job_Name')),
            ],
        ),
    ]
