# Generated by Django 2.2 on 2019-08-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolf', '0002_how_many_job_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='job_name',
            name='chain',
        ),
        migrations.DeleteModel(
            name='How_Many',
        ),
        migrations.DeleteModel(
            name='Job_Name',
        ),
    ]
