# Generated by Django 2.2 on 2019-08-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolf', '0003_auto_20190811_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wolf', models.PositiveIntegerField()),
                ('citizen', models.PositiveIntegerField()),
                ('hunter', models.PositiveIntegerField()),
                ('diviner', models.PositiveIntegerField()),
                ('traitor', models.PositiveIntegerField()),
                ('psychic', models.PositiveIntegerField()),
            ],
        ),
    ]
